#!/bin/sh
# Stage a kernel variant + its GSP firmware into a flat netboot tree, plus the
# GRUB fragment that boots it. Usage: scripts/netboot/mknetboot.sh [variant]
#
# This is mkiso.sh's staging WITHOUT the ISO: the same kernel.elf + fw/*.bin
# layout and the same module2 contract (ids MUST match src/drivers/gpu/gsp/firmware.zig
# MODULE_IDS), emitted as a plain directory that lemon.sh ships to the target and
# GRUB boots from local disk.
#
#   $BUILD_DIR/netboot/
#     kernel.elf          the multiboot2 kernel
#     fw/*.bin            the five decompressed GSP blobs (absent on a no-fw build)
#     kudos.cfg           multiboot2 + module2 + boot — `source`d by lemon's GRUB
#
# Why a sourced fragment and not a menuentry baked into lemon's grub.cfg: the
# module list changes with the firmware build, and this way the ENTIRE boot
# recipe ships with the tree. lemon's own GRUB entry is a fixed 3-line stub that
# never has to change again — no update-grub on every iteration.
set -e
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

BUILD_DIR="${BUILD_DIR:-build}"
VARIANT="${1:-kudos}"
KERNEL="$BUILD_DIR/bin/$VARIANT"
[ -f "$KERNEL" ] || { echo "mknetboot: kernel $KERNEL not found (run 'make build' first)" >&2; exit 1; }

# Where the tree lands ON THE TARGET. The GRUB fragment's paths are absolute
# within the boot filesystem, so this prefix is baked into kudos.cfg and must
# match lemon.sh's install location.
TARGET_DIR="${TARGET_DIR:-/boot/kudos}"

NETDIR="$BUILD_DIR/netboot"
rm -rf "$NETDIR"
mkdir -p "$NETDIR"
cp "$KERNEL" "$NETDIR/kernel.elf"

# GSP firmware staging — identical contract to mkiso.sh (see its comment for why
# the auto-detect default is deliberate rather than a silent fallback). Set
# GSP_FW_DIR="" to force the no-firmware build, which is the RIGHT first thing to
# boot on new bare metal: no GSP handoff means the 4090 is never touched, so a
# hang cannot wedge the card in a way that stalls the next POST.
GSP_MODULES=""
if [ -z "${GSP_FW_DIR+set}" ]; then
    if [ -d /lib/firmware/nvidia/ad102/gsp ]; then
        GSP_FW_DIR=/lib/firmware/nvidia/ad102/gsp
        echo "mknetboot: auto-detected GSP firmware at $GSP_FW_DIR (set GSP_FW_DIR= to disable)"
    fi
fi
if [ -n "$GSP_FW_DIR" ]; then
    [ -d "$GSP_FW_DIR" ] || { echo "mknetboot: GSP_FW_DIR '$GSP_FW_DIR' is not a directory" >&2; exit 1; }
    command -v zstd >/dev/null 2>&1 || { echo "mknetboot: zstd required to decompress GSP firmware" >&2; exit 1; }
    VER="${GSP_FW_VER:-570.144}"
    mkdir -p "$NETDIR/fw"
    GSP_IMG="${GSP_FW_GSP:-$GSP_FW_DIR/gsp-$VER.bin.zst}"
    stage_mod() {
        id="$1"; src="$2"
        [ -f "$src" ] || { echo "mknetboot: missing GSP blob for '$id': $src" >&2; exit 1; }
        zstd -d -q -f --stdout "$src" > "$NETDIR/fw/$id.bin"
        GSP_MODULES="$GSP_MODULES    module2 $TARGET_DIR/fw/$id.bin $id
"
        echo "  staged $id ($(stat -c%s "$NETDIR/fw/$id.bin") bytes)"
    }
    echo "Staging GSP firmware $VER from $GSP_FW_DIR:"
    stage_mod gsp_rm "$GSP_IMG"
    stage_mod booter_load   "$GSP_FW_DIR/booter_load-$VER.bin.zst"
    stage_mod booter_unload "$GSP_FW_DIR/booter_unload-$VER.bin.zst"
    stage_mod bootloader    "$GSP_FW_DIR/bootloader-$VER.bin.zst"
    stage_mod scrubber      "$GSP_FW_DIR/scrubber-$VER.bin.zst"
else
    echo "mknetboot: NO GSP firmware staged — kudos will run on the GRUB framebuffer"
fi

BUILD_NO="$(cat BUILD_NUMBER 2>/dev/null || echo '?')"

# ---------------------------------------------------------------------------
# Path A — DISK boot (fallback). The recipe lemon's on-disk GRUB stub sources
# after lemon.sh `arm` rsyncs this tree to /boot/kudos. `root` is already set by
# the stub's `search`, so these paths are absolute within lemon's filesystem.
# Kept because it is proven, and because it still boots when this laptop is off.
# ---------------------------------------------------------------------------
{
    echo "# kudos $VARIANT — generated by scripts/netboot/mknetboot.sh; do not edit"
    echo "echo 'kudos: loading $VARIANT (build $BUILD_NO)'"
    echo "multiboot2 $TARGET_DIR/kernel.elf"
    printf '%s' "$GSP_MODULES"
    echo "boot"
} > "$NETDIR/kudos.cfg"

# ---------------------------------------------------------------------------
# Path B — NETWORK boot (primary). Nothing is staged on lemon at all: its
# firmware PXE-boots, pulls the GRUB image below over TFTP from us, and that GRUB
# fetches the kernel over HTTP out of THIS DIRECTORY. So whatever is in
# build/netboot/ when lemon resets is what lemon runs — no rsync, no arming a
# stale tree, no way for the recipe and the blobs to disagree.
#
# Why the kernel comes over HTTP and not TFTP: it is ~31 MB, and TFTP is a
# lockstep ack-per-block protocol — minutes over wifi. GRUB's http module fetches
# it in seconds. TFTP still carries bootnetx64.efi itself, because that is the one
# file the FIRMWARE fetches and firmware only speaks TFTP.
#
# The GRUB image is built with prefix (tftp)/ so it looks for (tftp)/grub.cfg —
# `net_default_server` comes from the proxyDHCP handoff, so it finds its way back
# to us with nothing hard-coded.
# ---------------------------------------------------------------------------
SERVE_IP="${SERVE_IP:-$(ip route get "$("$(dirname "$0")/lemonip.sh")" 2>/dev/null | sed -n 's/.* src \([0-9.]*\).*/\1/p')}"
SERVE_IP="${SERVE_IP:-127.0.0.1}"
HTTP_PORT="${HTTP_PORT:-8099}"
HTTP="(http,$SERVE_IP:$HTTP_PORT)"

if command -v grub-mkimage >/dev/null 2>&1; then
    # `part_gpt`/`fat`/`search` are NOT here on purpose: this GRUB never touches a
    # local disk. It has exactly the modules for "come up on the NIC the firmware
    # already configured, read a config, multiboot2 a kernel over http".
    grub-mkimage -O x86_64-efi -o "$NETDIR/bootnetx64.efi" -p '(tftp)/' \
        efinet tftp http net normal multiboot2 configfile echo test reboot halt
    # HTTP first, TFTP as the fallback. HTTP is the fast path (the full image is
    # ~31 MB and TFTP's lockstep ack-per-block would crawl over wifi), but it is one
    # more moving part — a python server that must be up on a laptop that must be
    # awake. TFTP is already proven at this point in the boot: the firmware just used
    # it to fetch GRUB itself, so if we got here, TFTP works. Falling back to it
    # turns "the HTTP server is down" from a failed boot into a slow one.
    {
        echo "# kudos $VARIANT (build $BUILD_NO) — generated; served to lemon's netbooted GRUB"
        echo "set timeout=0"
        echo "set default=0"
        echo "menuentry 'kudos $VARIANT (build $BUILD_NO, netboot)' {"
        echo "    echo 'kudos: fetching kernel over http from $SERVE_IP:$HTTP_PORT'"
        echo "    if multiboot2 $HTTP/kernel.elf; then"
        echo "        echo 'kudos: kernel loaded over http'"
        printf '%s' "$GSP_MODULES" | sed "s#module2 $TARGET_DIR/#module2 $HTTP/#"
        echo "    else"
        echo "        echo 'kudos: http fetch failed — falling back to tftp (slower)'"
        echo "        multiboot2 /kernel.elf"
        printf '%s' "$GSP_MODULES" | sed "s#module2 $TARGET_DIR/#module2 /#"
        echo "    fi"
        echo "    boot"
        echo "}"
    } > "$NETDIR/grub.cfg"
    echo "mknetboot: netboot bootloader staged (serving from $SERVE_IP:$HTTP_PORT)"
else
    echo "mknetboot: grub-mkimage NOT FOUND — netboot path unavailable, disk path (lemon.sh arm) still works" >&2
fi

echo "Staged $ROOT/$NETDIR ($(du -sh "$NETDIR" | cut -f1), variant=$VARIANT)"
