//! Every OpenGL ES 1.1 entry point, by name.
//!
//! The list is maintained by hand against the OpenGL ES 1.1.12 Full Specification
//! and the Khronos header (GLES/gl.h), which declare the same 145 names.
//!
//! It exists so the entry-point surface cannot shrink unnoticed: gl.zig walks this
//! list at comptime and fails to build if any name has no decl. That checks the
//! names are PRESENT, not that what stands behind them conforms.

/// The C name as the specification spells it, and the decl gl.zig must expose.
pub const Entry = struct { gl: []const u8, decl: []const u8 };

pub const ALL = [_]Entry{
    .{ .gl = "glActiveTexture", .decl = "activeTexture" },
    .{ .gl = "glAlphaFunc", .decl = "alphaFunc" },
    .{ .gl = "glAlphaFuncx", .decl = "alphaFuncx" },
    .{ .gl = "glBindBuffer", .decl = "bindBuffer" },
    .{ .gl = "glBindTexture", .decl = "bindTexture" },
    .{ .gl = "glBlendFunc", .decl = "blendFunc" },
    .{ .gl = "glBufferData", .decl = "bufferData" },
    .{ .gl = "glBufferSubData", .decl = "bufferSubData" },
    .{ .gl = "glClear", .decl = "clear" },
    .{ .gl = "glClearColor", .decl = "clearColor" },
    .{ .gl = "glClearColorx", .decl = "clearColorx" },
    .{ .gl = "glClearDepthf", .decl = "clearDepthf" },
    .{ .gl = "glClearDepthx", .decl = "clearDepthx" },
    .{ .gl = "glClearStencil", .decl = "clearStencil" },
    .{ .gl = "glClientActiveTexture", .decl = "clientActiveTexture" },
    .{ .gl = "glClipPlanef", .decl = "clipPlanef" },
    .{ .gl = "glClipPlanex", .decl = "clipPlanex" },
    .{ .gl = "glColor4f", .decl = "color4f" },
    .{ .gl = "glColor4ub", .decl = "color4ub" },
    .{ .gl = "glColor4x", .decl = "color4x" },
    .{ .gl = "glColorMask", .decl = "colorMask" },
    .{ .gl = "glColorPointer", .decl = "colorPointer" },
    .{ .gl = "glCompressedTexImage2D", .decl = "compressedTexImage2D" },
    .{ .gl = "glCompressedTexSubImage2D", .decl = "compressedTexSubImage2D" },
    .{ .gl = "glCopyTexImage2D", .decl = "copyTexImage2D" },
    .{ .gl = "glCopyTexSubImage2D", .decl = "copyTexSubImage2D" },
    .{ .gl = "glCullFace", .decl = "cullFace" },
    .{ .gl = "glDeleteBuffers", .decl = "deleteBuffers" },
    .{ .gl = "glDeleteTextures", .decl = "deleteTextures" },
    .{ .gl = "glDepthFunc", .decl = "depthFunc" },
    .{ .gl = "glDepthMask", .decl = "depthMask" },
    .{ .gl = "glDepthRangef", .decl = "depthRangef" },
    .{ .gl = "glDepthRangex", .decl = "depthRangex" },
    .{ .gl = "glDisable", .decl = "disable" },
    .{ .gl = "glDisableClientState", .decl = "disableClientState" },
    .{ .gl = "glDrawArrays", .decl = "drawArrays" },
    .{ .gl = "glDrawElements", .decl = "drawElements" },
    .{ .gl = "glEnable", .decl = "enable" },
    .{ .gl = "glEnableClientState", .decl = "enableClientState" },
    .{ .gl = "glFinish", .decl = "finish" },
    .{ .gl = "glFlush", .decl = "flush" },
    .{ .gl = "glFogf", .decl = "fogf" },
    .{ .gl = "glFogfv", .decl = "fogfv" },
    .{ .gl = "glFogx", .decl = "fogx" },
    .{ .gl = "glFogxv", .decl = "fogxv" },
    .{ .gl = "glFrontFace", .decl = "frontFace" },
    .{ .gl = "glFrustumf", .decl = "frustumf" },
    .{ .gl = "glFrustumx", .decl = "frustumx" },
    .{ .gl = "glGenBuffers", .decl = "genBuffers" },
    .{ .gl = "glGenTextures", .decl = "genTextures" },
    .{ .gl = "glGetBooleanv", .decl = "getBooleanv" },
    .{ .gl = "glGetBufferParameteriv", .decl = "getBufferParameteriv" },
    .{ .gl = "glGetClipPlanef", .decl = "getClipPlanef" },
    .{ .gl = "glGetClipPlanex", .decl = "getClipPlanex" },
    .{ .gl = "glGetError", .decl = "getError" },
    .{ .gl = "glGetFixedv", .decl = "getFixedv" },
    .{ .gl = "glGetFloatv", .decl = "getFloatv" },
    .{ .gl = "glGetIntegerv", .decl = "getIntegerv" },
    .{ .gl = "glGetLightfv", .decl = "getLightfv" },
    .{ .gl = "glGetLightxv", .decl = "getLightxv" },
    .{ .gl = "glGetMaterialfv", .decl = "getMaterialfv" },
    .{ .gl = "glGetMaterialxv", .decl = "getMaterialxv" },
    .{ .gl = "glGetPointerv", .decl = "getPointerv" },
    .{ .gl = "glGetString", .decl = "getString" },
    .{ .gl = "glGetTexEnvfv", .decl = "getTexEnvfv" },
    .{ .gl = "glGetTexEnviv", .decl = "getTexEnviv" },
    .{ .gl = "glGetTexEnvxv", .decl = "getTexEnvxv" },
    .{ .gl = "glGetTexParameterfv", .decl = "getTexParameterfv" },
    .{ .gl = "glGetTexParameteriv", .decl = "getTexParameteriv" },
    .{ .gl = "glGetTexParameterxv", .decl = "getTexParameterxv" },
    .{ .gl = "glHint", .decl = "hint" },
    .{ .gl = "glIsBuffer", .decl = "isBuffer" },
    .{ .gl = "glIsEnabled", .decl = "isEnabled" },
    .{ .gl = "glIsTexture", .decl = "isTexture" },
    .{ .gl = "glLightModelf", .decl = "lightModelf" },
    .{ .gl = "glLightModelfv", .decl = "lightModelfv" },
    .{ .gl = "glLightModelx", .decl = "lightModelx" },
    .{ .gl = "glLightModelxv", .decl = "lightModelxv" },
    .{ .gl = "glLightf", .decl = "lightf" },
    .{ .gl = "glLightfv", .decl = "lightfv" },
    .{ .gl = "glLightx", .decl = "lightx" },
    .{ .gl = "glLightxv", .decl = "lightxv" },
    .{ .gl = "glLineWidth", .decl = "lineWidth" },
    .{ .gl = "glLineWidthx", .decl = "lineWidthx" },
    .{ .gl = "glLoadIdentity", .decl = "loadIdentity" },
    .{ .gl = "glLoadMatrixf", .decl = "loadMatrixf" },
    .{ .gl = "glLoadMatrixx", .decl = "loadMatrixx" },
    .{ .gl = "glLogicOp", .decl = "logicOp" },
    .{ .gl = "glMaterialf", .decl = "materialf" },
    .{ .gl = "glMaterialfv", .decl = "materialfv" },
    .{ .gl = "glMaterialx", .decl = "materialx" },
    .{ .gl = "glMaterialxv", .decl = "materialxv" },
    .{ .gl = "glMatrixMode", .decl = "matrixMode" },
    .{ .gl = "glMultMatrixf", .decl = "multMatrixf" },
    .{ .gl = "glMultMatrixx", .decl = "multMatrixx" },
    .{ .gl = "glMultiTexCoord4f", .decl = "multiTexCoord4f" },
    .{ .gl = "glMultiTexCoord4x", .decl = "multiTexCoord4x" },
    .{ .gl = "glNormal3f", .decl = "normal3f" },
    .{ .gl = "glNormal3x", .decl = "normal3x" },
    .{ .gl = "glNormalPointer", .decl = "normalPointer" },
    .{ .gl = "glOrthof", .decl = "orthof" },
    .{ .gl = "glOrthox", .decl = "orthox" },
    .{ .gl = "glPixelStorei", .decl = "pixelStorei" },
    .{ .gl = "glPointParameterf", .decl = "pointParameterf" },
    .{ .gl = "glPointParameterfv", .decl = "pointParameterfv" },
    .{ .gl = "glPointParameterx", .decl = "pointParameterx" },
    .{ .gl = "glPointParameterxv", .decl = "pointParameterxv" },
    .{ .gl = "glPointSize", .decl = "pointSize" },
    .{ .gl = "glPointSizePointerOES", .decl = "pointSizePointerOES" },
    .{ .gl = "glPointSizex", .decl = "pointSizex" },
    .{ .gl = "glPolygonOffset", .decl = "polygonOffset" },
    .{ .gl = "glPolygonOffsetx", .decl = "polygonOffsetx" },
    .{ .gl = "glPopMatrix", .decl = "popMatrix" },
    .{ .gl = "glPushMatrix", .decl = "pushMatrix" },
    .{ .gl = "glReadPixels", .decl = "readPixels" },
    .{ .gl = "glRotatef", .decl = "rotatef" },
    .{ .gl = "glRotatex", .decl = "rotatex" },
    .{ .gl = "glSampleCoverage", .decl = "sampleCoverage" },
    .{ .gl = "glSampleCoveragex", .decl = "sampleCoveragex" },
    .{ .gl = "glScalef", .decl = "scalef" },
    .{ .gl = "glScalex", .decl = "scalex" },
    .{ .gl = "glScissor", .decl = "scissor" },
    .{ .gl = "glShadeModel", .decl = "shadeModel" },
    .{ .gl = "glStencilFunc", .decl = "stencilFunc" },
    .{ .gl = "glStencilMask", .decl = "stencilMask" },
    .{ .gl = "glStencilOp", .decl = "stencilOp" },
    .{ .gl = "glTexCoordPointer", .decl = "texCoordPointer" },
    .{ .gl = "glTexEnvf", .decl = "texEnvf" },
    .{ .gl = "glTexEnvfv", .decl = "texEnvfv" },
    .{ .gl = "glTexEnvi", .decl = "texEnvi" },
    .{ .gl = "glTexEnviv", .decl = "texEnviv" },
    .{ .gl = "glTexEnvx", .decl = "texEnvx" },
    .{ .gl = "glTexEnvxv", .decl = "texEnvxv" },
    .{ .gl = "glTexImage2D", .decl = "texImage2D" },
    .{ .gl = "glTexParameterf", .decl = "texParameterf" },
    .{ .gl = "glTexParameterfv", .decl = "texParameterfv" },
    .{ .gl = "glTexParameteri", .decl = "texParameteri" },
    .{ .gl = "glTexParameteriv", .decl = "texParameteriv" },
    .{ .gl = "glTexParameterx", .decl = "texParameterx" },
    .{ .gl = "glTexParameterxv", .decl = "texParameterxv" },
    .{ .gl = "glTexSubImage2D", .decl = "texSubImage2D" },
    .{ .gl = "glTranslatef", .decl = "translatef" },
    .{ .gl = "glTranslatex", .decl = "translatex" },
    .{ .gl = "glVertexPointer", .decl = "vertexPointer" },
    .{ .gl = "glViewport", .decl = "viewport" },
};

/// 145 entry points. The Common profile's whole surface.
pub const COUNT: usize = ALL.len;
