#!/usr/bin/env bash
# The public-surface snapshot gate: widening a contract shows in the diff that did it
# (process.md §Change control, §11/§52). api_surface.txt is the committed, generated
# record of every top-level `pub` declaration in src/; this script regenerates it and
# fails on drift, so a surface change is always a reviewed line in the change that
# made it — never a silent absorption.
#
#   scripts/tests/apisnap.sh          gate: regenerate and diff against the committed snapshot
#   scripts/tests/apisnap.sh --write  accept the current surface as the new snapshot
set -uo pipefail
cd "$(dirname "$0")/../.."

SNAPSHOT=scripts/tests/api_surface.txt

generate() {
    echo "# Generated by scripts/tests/apisnap.sh — regenerate with --write, never edit."
    echo "# One line per top-level pub declaration in src/: the public surface, reviewable."
    find src -name '*.zig' ! -name '*_testroot.zig' | sort | while IFS= read -r f; do
        grep -n '^pub ' "$f" | sed -E "s/[ \t]+\{?[ \t]*$//; s|^([0-9]+):|$f: |"
    done
}

if [ "${1:-}" = "--write" ]; then
    generate > "$SNAPSHOT"
    echo "  api_surface.txt rewritten: $(grep -c '^src/' "$SNAPSHOT") pub declaration(s)"
    exit 0
fi

drift="$(diff "$SNAPSHOT" <(generate))"
if [ -n "$drift" ]; then
    echo "  ✗ the public surface drifted from the committed snapshot:"
    echo "$drift" | grep -E '^[<>]' | head -20 | sed 's/^/      /'
    echo "      review the contract change, then: scripts/tests/apisnap.sh --write"
    exit 1
fi
echo "  ✓ public surface matches the committed snapshot ($(grep -c '^src/' "$SNAPSHOT") pub declaration(s))"
